services:
  - type: web
    name: rentmycar-server
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        scope: run_and_build
      - key: JWT_SECRET
        scope: run_and_build
      - key: IMAGEKIT_PUBLIC_KEY
        scope: run_and_build
      - key: IMAGEKIT_PRIVATE_KEY
        scope: run_and_build
      - key: IMAGEKIT_URL_ENDPOINT
        scope: run_and_build
      - key: CLIENT_URL
        scope: run_and_build
      - key: NODE_ENV
        value: production
